# Site settings
title: 은수로그
main_title: WELCOME | 은수로그
description: "Yet Another Minimal Theme"
url:  "https://eunsu-joo.github.io" # Actual base url of the website
baseurl: ""           # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "은수 | Julie"
  email: "julieand1024.com"
  url: "https://eunsu-joo.github.io"
permalink: /:year/:month/:day/:title:output_ext

#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 3
paginate_path: "/page:num/"

#SEO
logo: /assets/img/logo.svg
social:
  links: #List your social links here
    - https://www.github.com/eunsu-joo
    - https://instagram.com/lifeisganzi
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
default_lang: 'ko'
exclude_from_localization: ['javascript', 'images', 'css']

#Highlighter
kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never