# Site settings
title: 은수로그
main_title: WELCOME | 은수로그
description: "개발자 개발자은수 은수로그 칸둥 은수 Julie"
url:  "https://eunsu-joo.github.io" # Actual base url of the website
baseurl: ""           # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "은수 | Julie"
  email: "julieand1024.com"
  url: "https://eunsu-joo.github.io"
permalink: /:year/:month/:day/:title:output_ext

#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 10
paginate_path: "/page:num/"

#SEO
logo: /assets/img/logo.svg
#Highlighter
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3

#Sass
sass:
  style: compressed
  sourcemap: never

defaults:
  - scope:
      path: "" # an empty string here means all files of a type
      type: "posts"
    values:
      layout: "post"
      image: ""
      categories: ""
      description: ""
